version: '3.7'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
      - "27017:27017"
    networks: 
      - asp-microservice
    volumes:
      - mongo_data:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    ports:
      - "6379:6379"
    networks: 
      - asp-microservice

  discountdb:
    image: postgres
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
        - "5432:5432"
    networks: 
      - asp-microservice
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    networks: 
      - asp-microservice
  
  portainer:
    image: portainer/portainer-ce 
    container_name: portainer
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks: 
      - asp-microservice

networks: 
  asp-microservice:
    driver: bridge  

volumes:
  mongo_data:
  postgres_data:
  portainer_data:
      driver: local